Fix the test failure with the latest `findpython` installed.
